# Generated by Django 2.2.12 on 2020-07-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200711_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
