# Generated by Django 2.2.12 on 2020-07-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200712_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
