# Generated by Django 2.2.12 on 2020-07-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200712_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
